# Generated by Django 6.0 on 2026-05-01 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель (напр. Tucson)')),
                ('body_style', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Кросовер'), ('electric', 'Електромобіль'), ('hatchback', 'Хетчбек')], max_length=20, verbose_name='Тип кузова')),
                ('year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('engine_info', models.CharField(help_text='Напр. 2.0 Multi Point Injection', max_length=100, verbose_name='Двигун')),
                ('power', models.IntegerField(verbose_name='Потужність (к.с.)')),
                ('transmission', models.CharField(default='6MT / 6AT', max_length=50, verbose_name='Трансмісія')),
                ('image', models.ImageField(upload_to='hyundai_cars/', verbose_name='Фото авто')),
                ('description', models.TextField(blank=True, verbose_name='Опис моделі та переваг')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно в салоні')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('vin_code', models.CharField(blank=True, max_length=17, verbose_name='VIN-код авто')),
                ('service_type', models.CharField(max_length=100, verbose_name='Тип робіт (ТО, діагностика)')),
                ('date', models.DateTimeField(verbose_name='Дата запису')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва запчастини')),
                ('part_number', models.CharField(blank=True, max_length=50, verbose_name='Артикул (OEM)')),
                ('category', models.CharField(max_length=100, verbose_name='Категорія (Фільтри, Гальма тощо)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
            ],
        ),
        migrations.CreateModel(
            name='TestDriveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Клієнт')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date', models.DateTimeField(verbose_name='Час тест-драйву')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.car', verbose_name='Обрана модель')),
            ],
        ),
    ]
