# Generated by Django 6.0 on 2026-05-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='email',
            field=models.CharField(default='test@test.com', max_length=100, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='last_name',
            field=models.CharField(default='-', max_length=100, verbose_name='Прізвище'),
            preserve_default=False,
        ),
    ]
