# Generated by Django 6.0 on 2026-05-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0002_servicebooking_email_servicebooking_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivebooking',
            name='last_name',
            field=models.CharField(default='-', max_length=100, verbose_name='Прізвище'),
            preserve_default=False,
        ),
    ]
